version: '3.8'

services:
  norseai-backend:
    build: .
    container_name: norseai-backend
    ports:
      - "6700:6700"
    #environment:
    #  - PYTHONPATH=/norseai-backend
    env_file:
      - stack.env
    # volumes:
    #   - ./src:/app/src
    restart: unless-stopped
    networks:
      - norseai

networks:
  norseai:
    external: true
