import logging

DEBUG_LEVEL = 2
'''
0 -> Error logging only
1 -> basic logging info (user state, model thinking, info, errors)
2 -> debug (basic logging info + detailed procceses)
'''


# knowledge graph for combonatorics AMC 8
knowledge_graph = {
    # Algebra
    "Arithmetic": 0.0,
    "Order of Operations (PEMDAS)": 0.0,
    "Manipulating Fractions": 0.0,
    "Variables": 0.0,
    "Expressions and Evaluation": 0.0,
    "Substitution": 0.0,
    "Distance = Rate*Time": 0.0,
    "Linear Equations": 0.0,
    "System of Equations": 0.0,
    "Inequalities (Linear and Basic Quadratic)": 0.0,
    "Absolute Value": 0.0,
    "Ratios and Proportions": 0.0,
    "Percents, Percent of Change": 0.0,
    "Distributions": 0.0,
    "Perfect Squares": 0.0,
    "Difference of Squares": 0.0,
    "Factoring Polynomials": 0.0,
    "Factoring by Grouping": 0.0,
    "Quadratic Formula": 0.0,
    "Completing the Square": 0.0,
    "Vieta's Formulas: Sum and Product of the Roots": 0.0,
    "Calculations with Exponents": 0.0,
    "Laws of Exponents": 0.0,
    "Negative Exponents": 0.0,
    "Fractional Exponents": 0.0,
    "Square Roots and Nested Square Roots": 0.0,
    "Radicals (Simplifying, Multiplying, Rationalizing Denominators)": 0.0,
    "Mean, Harmonic Mean, Median, Mode, Range": 0.0,
    "Weighted Averages": 0.0,
    "Arithmetic Sequences and Series": 0.0,
    "Geometric Sequences and Series": 0.0,
    "Finite Sums (Σ Notation Basics)": 0.0,
    "Continued Fractions": 0.0,
    "Calculations with Logarithms": 0.0,
    "Exponential Growth and Decay (Basic)": 0.0,
    "Functions (Input-Output, Function Notation f(x))": 0.0,
    "Graph Problems": 0.0,
    "Graphing Linear Equations": 0.0,
    "Graphing Simple Quadratics": 0.0,
    "Slope-Intercept Form": 0.0,
    "Point-Slope Form": 0.0,
    "Parallel and Perpendicular Lines": 0.0,
    "Symmetry in Graphs (Even/Odd Functions, Reflection)": 0.0,

    # Geometry
    "Points": 0.0,
    "Lines": 0.0,
    "Planes": 0.0,
    "Distance Formula": 0.0,
    "Angles": 0.0,
    "Angle Bisectors": 0.0,
    "Perpendicular Bisectors": 0.0,
    "Parallel Lines & Transversals": 0.0,
    "Vertical Angles": 0.0,
    "Area": 0.0,
    "Perimeter": 0.0,
    "Sum of Interior Angles of Polygon": 0.0,
    "Exterior Angle Theorem": 0.0,
    "Triangles": 0.0,
    "Isosceles Triangles": 0.0,
    "Equilateral Triangles": 0.0,
    "Right Triangles": 0.0,
    "Inscribed Triangle": 0.0,
    "Circumscribed Triangle": 0.0,
    "Inradius": 0.0,
    "Circumradius": 0.0,
    "30-60-90": 0.0,
    "45-45-90": 0.0,
    "Pythagorean Theorem": 0.0,
    "Heron's Formula": 0.0,
    "Quadrilaterals": 0.0,
    "Parallelograms": 0.0,
    "Trapezoids": 0.0,
    "Isosceles Trapezoids": 0.0,
    "Kites": 0.0,
    "Rhombus": 0.0,
    "Rectangles": 0.0,
    "Squares": 0.0,
    "Cyclic Quadrilaterals": 0.0,
    "Circles": 0.0,
    "Arcs": 0.0,
    "Sectors": 0.0,
    "Segments of a Circle": 0.0,
    "Chords": 0.0,
    "Tangent Lines": 0.0,
    "Secants": 0.0,
    "Power of a Point": 0.0,
    "Polygons": 0.0,
    "Regular Polygons": 0.0,
    "Altitudes": 0.0,
    "Medians": 0.0,
    "Angle Bisectors (Triangle)": 0.0,
    "Centroid": 0.0,
    "Orthocenter": 0.0,
    "Circumcenter": 0.0,
    "Incenter": 0.0,
    "Faces": 0.0,
    "Vertices": 0.0,
    "Edges": 0.0,
    "Cubes": 0.0,
    "Rectangular Prisms": 0.0,
    "Spheres": 0.0,
    "Cylinders": 0.0,
    "Cones": 0.0,
    "Pyramids": 0.0,
    "Frustums": 0.0,
    "Nets of 3D Solids": 0.0,
    "Cross-Sections of 3D Solids": 0.0,
    "Euler's Formula for Polyhedra": 0.0,
    "Volume": 0.0,
    "Surface Area": 0.0,
    "Coordinate Geometry": 0.0,
    "Shoelace Theorem": 0.0,
    "Pick's Theorem": 0.0,
    "Transformations": 0.0,
    "Reflections": 0.0,
    "Rotations": 0.0,
    "Translations": 0.0,
    "Dilations": 0.0,
    "Similarity": 0.0,
    "Congruence": 0.0,
    "Law of Cosine": 0.0,
    "Law of Sine": 0.0,

    # Number Theory
    "Prime Numbers": 0.0,
    "Divisibility": 0.0,
    "Factor Counting": 0.0,
    "Number of Divisors": 0.0,
    "Sum of the Factors": 0.0,
    "Product of the Factors": 0.0,
    "GCD": 0.0,
    "LCM": 0.0,
    "Arithmetic Progressions": 0.0,
    "Properties of Even and Odd Numbers": 0.0,
    "Units Digit Problems": 0.0,
    "Digit Sums": 0.0,
    "Digit Reversals": 0.0,
    "Palindromes": 0.0,
    "Base Conversions": 0.0,
    "Modular Arithmetic": 0.0,
    "Remainder Problems": 0.0,
    "Modular Inverse": 0.0,
    "Chinese Remainder Theorem": 0.0,
    "Factorial Divisibility": 0.0,
    "Perfect Numbers": 0.0,
    "Perfect Squares": 0.0,
    "Cubic Patterns": 0.0,
    "Quadratic Residues": 0.0,
    "Exponent Puzzles": 0.0,
    "Sum/Product of Digits": 0.0,
    "Fermat's Little Theorem": 0.0,
    "Euler's Theorem": 0.0,
    "Repeating Decimals/Fractions": 0.0,

    # Combinatorics
    "Distinguishability": 0.0,
    "Counting Independent Events": 0.0,
    "Factorials": 0.0,
    "Permutations": 0.0,
    "Permutations with Restrictions": 0.0,
    "Combinations": 0.0,
    "Casework": 0.0,
    "Restrictions": 0.0,
    "Overcounting": 0.0,
    "Constructive Counting": 0.0,
    "Counting with Symmetry": 0.0,
    "The Pigeonhole Principle": 0.0,
    "Recursive Counting": 0.0,
    "Probability": 0.0,
    "Multiplying Probabilities": 0.0,
    "Expected Value": 0.0,
    "Linearity of Expectation": 0.0,
    "Probability with Casework": 0.0,
    "Complementary Probability": 0.0,
    "Conditional Probability": 0.0,
    "Recursion in Probability": 0.0,
    "Advanced Probability with Combinations": 0.0,
    "Distributions": 0.0,
    "Combinations and Pascal's Triangle": 0.0,
    "The Binomial Theorem": 0.0,
    "Combinatorial Identities (Hockey Sum, Sum of Last Two, Etc)": 0.0,
    "Set Notation": 0.0,
    "Venn Diagrams": 0.0,
    "Truth and Logic": 0.0,
    "Bijective Counting (Paths on a Grid, Etc.)": 0.0,
    "Beyond Casework": 0.0,
    "Complimentary Counting": 0.0,
    "Stars and Bars: With Restrictions": 0.0,
    "Stars and Bars: Without Restrictions": 0.0,

    # Probability
    "Compound Events": 0.0,
    "Dependent Events": 0.0,
    "Independent Events": 0.0,
    "Replacement": 0.0,
    "Cards": 0.0,
    "Marbles": 0.0,
    "Dice Probabilities": 0.0,
    "Sequences of Coin Flips": 0.0,
    "Games & Random Processes": 0.0,
    "Geometric Probability": 0.0,
    "Casework in Probability": 0.0,
    "Counting & Symmetry in Probability": 0.0,
    "Number Theory in Probability": 0.0,
    "Arrangements & Orderings in Probability": 0.0,
    "Probability with Inequalities": 0.0,
    "Complementary Counting in Probability": 0.0,
    "Probability with Fractions & Ratios": 0.0,
    "Multiple-Stage Probability": 0.0,
    "Conditional Probability": 0.0,
    "Random Selection on Grids / Coordinate Planes": 0.0,
    "Continuous/Interval Selection": 0.0,
    "Probability and Symmetry": 0.0,
    "Overcounting & Distinguishability in Probability": 0.0
}

concepts = [
    # Algebra subtopics
    "arithmetic",
    "order of operations (PEMDAS)",
    "manipulating fractions",
    "variables",
    "expressions and evaluation",
    "substitution",
    "distance = rate*time",
    "linear equations",
    "system of equations",
    "inequalities (linear and basic quadratic)",
    "absolute value",
    "ratios and proportions",
    "percents, percent of change",
    "distributions",
    "perfect squares",
    "difference of squares",
    "factoring polynomials",
    "factoring by grouping",
    "quadratic formula",
    "completing the square",
    "Vieta's formulas: sum and product of the roots",
    "calculations with exponents",
    "laws of exponents",
    "negative exponents",
    "fractional exponents",
    "square roots and nested square roots",
    "radicals (simplifying, multiplying, rationalizing denominators)",
    "mean, harmonic mean, median, mode, range",
    "weighted averages",
    "arithmetic sequences and series",
    "geometric sequences and series",
    "finite sums (Σ notation basics)",
    "continued fractions",
    "calculations with logarithms",
    "exponential growth and decay (basic)",
    "functions (input-output, function notation f(x))",
    "graph problems",
    "graphing linear equations",
    "graphing simple quadratics",
    "slope-intercept form",
    "point-slope form",
    "parallel and perpendicular lines",
    "symmetry in graphs (even/odd functions, reflection)",

    # Geometry subtopics
    "points",
    "lines",
    "planes",
    "distance formula",
    "angles",
    "angle bisectors",
    "perpendicular bisectors",
    "parallel lines & transversals",
    "vertical angles",
    "area",
    "perimeter",
    "sum of interior angles of polygon",
    "exterior angle theorem",
    "triangles",
    "isosceles triangles",
    "equilateral triangles",
    "right triangles",
    "inscribed triangle",
    "circumscribed triangle",
    "inradius",
    "circumradius",
    "30-60-90",
    "45-45-90",
    "pythagorean theorem",
    "heron's formula",
    "quadrilaterals",
    "parallelograms",
    "trapezoids",
    "isosceles trapezoids",
    "kites",
    "rhombus",
    "rectangles",
    "squares",
    "cyclic quadrilaterals",
    "circles",
    "arcs",
    "sectors",
    "segments of a circle",
    "chords",
    "tangent lines",
    "secants",
    "power of a point",
    "polygons",
    "regular polygons",
    "altitudes",
    "medians",
    "angle bisectors (triangle)",
    "centroid",
    "orthocenter",
    "circumcenter",
    "incenter",
    "faces",
    "vertices",
    "edges",
    "cubes",
    "rectangular prisms",
    "spheres",
    "cylinders",
    "cones",
    "pyramids",
    "frustums",
    "nets of 3D solids",
    "cross-sections of 3D solids",
    "euler's formula for polyhedra",
    "volume",
    "surface area",
    "coordinate geometry",
    "shoelace theorem",
    "pick's theorem",
    "transformations",
    "reflections",
    "rotations",
    "translations",
    "dilations",
    "similarity",
    "congruence",
    "law of cosine",
    "law of sine",

    # Number theory subtopics
    "prime numbers",
    "divisibility",
    "factor counting",
    "number of divisors",
    "sum of the factors",
    "product of the factors",
    "gcd",
    "lcm",
    "arithmetic progressions",
    "properties of even and odd numbers",
    "units digit problems",
    "digit sums",
    "digit reversals",
    "palindromes",
    "base conversions",
    "modular arithmetic",
    "remainder problems",
    "modular inverse",
    "chinese remainder theorem",
    "factorial divisibility",
    "perfect numbers",
    "perfect squares",
    "cubic patterns",
    "quadratic residues",
    "exponent puzzles",
    "sum/product of digits",
    "fermat's little theorem",
    "euler's theorem",
    "repeating decimals/fractions",

    # Combinatorics subtopics
    "distinguishability",
    "counting independent events",
    "factorials",
    "permutations",
    "permutations with restrictions",
    "combinations",
    "casework",
    "restrictions",
    "overcounting",
    "constructive counting",
    "counting with symmetry",
    "the pigeonhole principle",
    "recursive counting",
    "probability",
    "multiplying probabilities",
    "expected value",
    "linearity of expectation",
    "probability with casework",
    "complementary probability",
    "conditional probability",
    "recursion in probability",
    "advanced probability with combinations",
    "distributions",
    "combinations and pascal's triangle",
    "the binomial theorem",
    "combinatorial identities(hockey sum, sum of last two, etc)",
    "set notation",
    "venn diagrams",
    "truth and logic",
    "bijective counting(paths on a grid, etc.)",
    "beyond casework",
    "complimentary counting",
    "stars and bars: with restrictions",
    "stars and bars: without restrictions",

    # Probability subtopics
    "compound events",
    "dependent events",
    "independent events",
    "replacement",
    "cards",
    "marbles",
    "dice probabilities",
    "sequences of coin flips",
    "games & random processes",
    "geometric probability",
    "casework in probability",
    "counting & symmetry in probability",
    "number theory in probability",
    "arrangements & orderings in probability",
    "probability with inequalities",
    "complementary counting in probability",
    "probability with fractions & ratios",
    "multiple-stage probability",
    "conditional probability",
    "random selection on grids / coordinate planes",
    "continuous/interval selection",
    "probability and symmetry",
    "overcounting & distinguishability in probability"
] # list of concepts that matches knowledge graph

def convert_messages_to_dict(messages, student_id):
    """
    Converts a list of HumanMessage and AIMessage objects to a list of dictionaries.
    
    Args:
        messages: List containing HumanMessage and AIMessage objects
        
    Returns:
        List of dictionaries with 'student'/'teacher' keys and content values
    """
    result = []
    
    for message in messages:
        # Get the class name to determine message type
        message_type = message.__class__.__name__
        
        if message_type == 'HumanMessage':
            result.append({'student_id': student_id, 'role': 'student', 'content': message.content})
        elif message_type == 'AIMessage':
            result.append({'student_id': student_id, 'role': 'teacher', 'content': message.content})
    
    return result

def set_logger(name):
    # Configure logging
    logging.basicConfig(level=logging.INFO)
    return logging.getLogger(name)

def log(message, logger, level):
    if DEBUG_LEVEL >= level:
        return logger.info(message)
