amc8_knowledge_graph = {
    "arithmetic": 0.0,
    "logic reasoning": 0.0,
    "order of operations (pemdas)": 0.0,
    "manipulating fractions": 0.0,
    "variables": 0.0,
    "expressions and evaluation": 0.0,
    "substitution": 0.0,
    "distance = rate*time": 0.0,
    "linear equations": 0.0,
    "system of equations": 0.0,
    "inequalities": 0.0,
    "absolute value": 0.0,
    "ratios and proportions": 0.0,
    "percents, percent of change": 0.0,
    "distributions": 0.0,
    "perfect squares": 0.0,
    "difference of squares": 0.0,
    "factoring polynomials": 0.0,
    "quadratic formula": 0.0,
    "completing the square": 0.0,
    "Vieta's formulas: sum and product of the roots": 0.0,
    "calculations with exponents": 0.0,
    "laws of exponents": 0.0,
    "negative exponents": 0.0,
    "fractional exponents": 0.0,
    "square roots and nested square roots": 0.0,
    "radicals (simplifying, multiplying, rationalizing denominators)": 0.0,
    "mean, harmonic mean, median, mode, range": 0.0,
    "weighted averages": 0.0,
    "arithmetic sequences and series": 0.0,
    "geometric sequences and series": 0.0,
    "finite sums": 0.0,
    "continued fractions": 0.0,
    "calculations with logarithms": 0.0,
    "exponential growth and decay": 0.0,
    "functions, function notation": 0.0,
    "graph problems": 0.0,
    "graphing linear equations": 0.0,
    "graphing quadratics": 0.0,
    "slope-intercept form": 0.0,
    "point-slope form": 0.0,
    "parallel and perpendicular lines": 0.0,
    "symmetry in graphs": 0.0,
    "points": 0.0,
    "lines": 0.0,
    "planes": 0.0,
    "distance formula": 0.0,
    "angles": 0.0,
    "angle bisectors": 0.0,
    "perpendicular bisectors": 0.0,
    "parallel lines & transversals": 0.0,
    "vertical angles": 0.0,
    "area": 0.0,
    "perimeter": 0.0,
    "sum of interior angles of polygon": 0.0,
    "exterior angle theorem": 0.0,
    "triangles": 0.0,
    "isosceles triangles": 0.0,
    "equilateral triangles": 0.0,
    "right triangles": 0.0,
    "inscribed triangle": 0.0,
    "circumscribed triangle": 0.0,
    "inradius": 0.0,
    "circumradius": 0.0,
    "30-60-90": 0.0,
    "45-45-90": 0.0,
    "pythagorean theorem": 0.0,
    "heron's formula": 0.0,
    "quadrilaterals": 0.0,
    "parallelograms": 0.0,
    "trapezoids": 0.0,
    "isosceles trapezoids": 0.0,
    "kites": 0.0,
    "rhombus": 0.0,
    "rectangles": 0.0,
    "squares": 0.0,
    "cyclic quadrilaterals": 0.0,
    "circles": 0.0,
    "arcs": 0.0,
    "sectors": 0.0,
    "segments of a circle": 0.0,
    "chords": 0.0,
    "tangent lines": 0.0,
    "secants": 0.0,
    "power of a point": 0.0,
    "polygons": 0.0,
    "regular polygons": 0.0,
    "altitudes": 0.0,
    "medians": 0.0,
    "centroid": 0.0,
    "orthocenter": 0.0,
    "circumcenter": 0.0,
    "incenter": 0.0,
    "faces": 0.0,
    "vertices": 0.0,
    "edges": 0.0,
    "cubes": 0.0,
    "rectangular prisms": 0.0,
    "spheres": 0.0,
    "cylinders": 0.0,
    "cones": 0.0,
    "pyramids": 0.0,
    "frustums": 0.0,
    "nets of 3d solids": 0.0,
    "cross-sections of 3d solids": 0.0,
    "euler's formula for polyhedra": 0.0,
    "volume": 0.0,
    "surface area": 0.0,
    "coordinate geometry": 0.0,
    "shoelace theorem": 0.0,
    "pick's theorem": 0.0,
    "transformations": 0.0,
    "reflections": 0.0,
    "rotations": 0.0,
    "translations": 0.0,
    "dilations": 0.0,
    "similarity": 0.0,
    "congruence": 0.0,
    "law of cosine": 0.0,
    "law of sine": 0.0,
    "prime numbers": 0.0,
    "divisibility": 0.0,
    "factor counting": 0.0,
    "number of divisors": 0.0,
    "sum of the factors": 0.0,
    "product of the factors": 0.0,
    "gcd": 0.0,
    "lcm": 0.0,
    "arithmetic progressions": 0.0,
    "properties of even and odd numbers": 0.0,
    "units digit problems": 0.0,
    "digit sums": 0.0,
    "digit reversals": 0.0,
    "palindromes": 0.0,
    "base conversions": 0.0,
    "modular arithmetic": 0.0,
    "remainder problems": 0.0,
    "modular inverse": 0.0,
    "chinese remainder theorem": 0.0,
    "factorial divisibility": 0.0,
    "perfect numbers": 0.0,
    "perfect squares": 0.0,
    "cubic patterns": 0.0,
    "quadratic residues": 0.0,
    "exponent puzzles": 0.0,
    "sum/product of digits": 0.0,
    "fermat's little theorem": 0.0,
    "euler's theorem": 0.0,
    "repeating decimals/fractions": 0.0,
    "distinguishability": 0.0,
    "counting independent events": 0.0,
    "factorials": 0.0,
    "permutations": 0.0,
    "permutations with restrictions": 0.0,
    "combinations": 0.0,
    "casework": 0.0,
    "restrictions": 0.0,
    "overcounting": 0.0,
    "constructive counting": 0.0,
    "counting with symmetry": 0.0,
    "the pigeonhole principle": 0.0,
    "recursive counting": 0.0,
    "multiplying probabilities": 0.0,
    "expected value": 0.0,
    "linearity of expectation": 0.0,
    "complementary probability": 0.0,
    "conditional probability": 0.0,
    "recursion in probability": 0.0,
    "advanced probability with combinations": 0.0,
    "distributions": 0.0,
    "combinations and pascal's triangle": 0.0,
    "the binomial theorem": 0.0,
    "combinatorial identities(hockey sum, sum of last two, etc)": 0.0,
    "set notation": 0.0,
    "venn diagrams": 0.0,
    "truth and logic": 0.0,
    "bijective counting": 0.0,
    "beyond casework": 0.0,
    "complementary counting": 0.0,
    "stars and bars: with restrictions": 0.0,
    "stars and bars: without restrictions": 0.0,
    "compound events": 0.0,
    "dependent events": 0.0,
    "independent events": 0.0,
    "replacement": 0.0,
    "cards": 0.0,
    "marbles": 0.0,
    "dice probabilities": 0.0,
    "sequences of coin flips": 0.0,
    "games & random processes": 0.0,
    "geometric probability": 0.0,
    "casework in probability": 0.0,
    "counting & symmetry in probability": 0.0,
    "number theory in probability": 0.0,
    "probability with inequalities": 0.0,
    "random selection on grids / coordinate planes": 0.0,
    "continuous/interval selection": 0.0,
    "overcounting & distinguishability in probability": 0.0,
}



amc8_concepts = [
    # Algebra subtopics
    "arithmetic",
    "logic reasoning",
    "order of operations (pemdas)",
    "manipulating fractions",
    "variables",
    "expressions and evaluation",
    "substitution",
    "distance = rate*time",
    "linear equations",
    "system of equations",
    "inequalities",
    "absolute value",
    "ratios and proportions",
    "percents, percent of change",
    "distributions",
    "perfect squares",
    "difference of squares",
    "factoring polynomials",
    "quadratic formula",
    "completing the square",
    "Vieta's formulas: sum and product of the roots",
    "calculations with exponents",
    "laws of exponents",
    "negative exponents",
    "fractional exponents",
    "square roots and nested square roots",
    "radicals (simplifying, multiplying, rationalizing denominators)",
    "mean, harmonic mean, median, mode, range",
    "weighted averages",
    "arithmetic sequences and series",
    "geometric sequences and series",
    "finite sums",
    "continued fractions",
    "calculations with logarithms",
    "exponential growth and decay",
    "functions, function notation",
    "graph problems",
    "graphing linear equations",
    "graphing quadratics",
    "slope-intercept form",
    "point-slope form",
    "parallel and perpendicular lines",
    "symmetry in graphs",

    # Geometry subtopics
    "points",
    "lines",
    "planes",
    "distance formula",
    "angles",
    "angle bisectors",
    "perpendicular bisectors",
    "parallel lines & transversals",
    "vertical angles",
    "area",
    "perimeter",
    "sum of interior angles of polygon",
    "exterior angle theorem",
    "triangles",
    "isosceles triangles",
    "equilateral triangles",
    "right triangles",
    "inscribed triangle",
    "circumscribed triangle",
    "inradius",
    "circumradius",
    "30-60-90",
    "45-45-90",
    "pythagorean theorem",
    "heron's formula",
    "quadrilaterals",
    "parallelograms",
    "trapezoids",
    "isosceles trapezoids",
    "kites",
    "rhombus",
    "rectangles",
    "squares",
    "cyclic quadrilaterals",
    "circles",
    "arcs",
    "sectors",
    "segments of a circle",
    "chords",
    "tangent lines",
    "secants",
    "power of a point",
    "polygons",
    "regular polygons",
    "altitudes",
    "medians",
    "centroid",
    "orthocenter",
    "circumcenter",
    "incenter",
    "faces",
    "vertices",
    "edges",
    "cubes",
    "rectangular prisms",
    "spheres",
    "cylinders",
    "cones",
    "pyramids",
    "frustums",
    "nets of 3d solids",
    "cross-sections of 3d solids",
    "euler's formula for polyhedra",
    "volume",
    "surface area",
    "coordinate geometry",
    "shoelace theorem",
    "pick's theorem",
    "transformations",
    "reflections",
    "rotations",
    "translations",
    "dilations",
    "similarity",
    "congruence",
    "law of cosine",
    "law of sine",

    # Number theory subtopics
    "prime numbers",
    "divisibility",
    "factor counting",
    "number of divisors",
    "sum of the factors",
    "product of the factors",
    "gcd",
    "lcm",
    "arithmetic progressions",
    "properties of even and odd numbers",
    "units digit problems",
    "digit sums",
    "digit reversals",
    "palindromes",
    "base conversions",
    "modular arithmetic",
    "remainder problems",
    "modular inverse",
    "chinese remainder theorem",
    "factorial divisibility",
    "perfect numbers",
    "perfect squares",
    "cubic patterns",
    "quadratic residues",
    "exponent puzzles",
    "sum/product of digits",
    "fermat's little theorem",
    "euler's theorem",
    "repeating decimals/fractions",

    # Combinatorics and probability subtopics
    "distinguishability",
    "counting independent events",
    "factorials",
    "permutations",
    "permutations with restrictions",
    "combinations",
    "casework",
    "restrictions",
    "overcounting",
    "constructive counting",
    "counting with symmetry",
    "the pigeonhole principle",
    "recursive counting",
    "multiplying probabilities",
    "expected value",
    "linearity of expectation",
    "complementary probability",
    "conditional probability",
    "recursion in probability",
    "advanced probability with combinations",
    "distributions",
    "combinations and pascal's triangle",
    "the binomial theorem",
    "combinatorial identities(hockey sum, sum of last two, etc)",
    "set notation",
    "venn diagrams",
    "truth and logic",
    "bijective counting",
    "beyond casework",
    "complementary counting",
    "stars and bars: with restrictions",
    "stars and bars: without restrictions",
    "compound events",
    "dependent events",
    "independent events",
    "replacement",
    "cards",
    "marbles",
    "dice probabilities",
    "sequences of coin flips",
    "games & random processes",
    "geometric probability",
    "casework in probability",
    "counting & symmetry in probability",
    "number theory in probability",
    "probability with inequalities",
    "random selection on grids / coordinate planes",
    "continuous/interval selection",
    "overcounting & distinguishability in probability"
] # list of concepts that matches knowledge graph

